@endpoint = http://localhost:5000/api

GET {{endpoint}}

###
POST {{endpoint}}/register
Content-Type: application/json

{
  "username": "Jesus2",
  "password": "jesusroolz"
}

###
POST {{endpoint}}/login
Content-Type: application/json

{
  "username": "Jesus",
  "password": "jesusroolz"
}