@endpoint = http://localhost:5000/api

GET {{endpoint}}

###
GET {{endpoint}}/users
username: Jesus2
password: jesusroolz

###
POST {{endpoint}}/register
Content-Type: application/json

{
  "username": "Jesus2",
  "password": "jesusroolz"
}

###
POST {{endpoint}}/auth/login
username: Jesus
password: jesusroolz